### ISSUE TITLE
where is the output directory?

### ISSUE THREAD

**Issue by yzslry** [SamusRam/hpa-single-cell#1]
I notice that there is "output" directory in the file data/utils, but I can't find it in this project.

**Comment by SamusRam** [comment]
@liruiyuan1 , thank you for your interest in this project!

Originally, I put both "input" and "output" directories on the same folder level as the root `hpa-single-cell` folder.

I.e., on my machine the folder structure currently looks like

├── hpa-single-cell
│   ├── src
│   └── orchestration_scripts
├── input
└── output

You can see it in the README.md, where I clarify what should be downloaded into `../input`. Also, you might have noticed that some scripts populate `../input` (e.g., `src.preprocessing.generate_cell_bboxes` stores the bounding boxes with masks into `../input/cell_bboxes_train`), while some scripts populate `../output` (e.g. trained models are being stored into the `../output` folder).

Let me refactor the project so that both `input` and `output` folders would be included in this repo.

**Comment by SamusRam** [comment]
@liruiyuan1 , I've included folders `output` and `input` in the repo.

Therefore, now the project structure is
├── hpa-single-cell
│ ├── src
│ ├── orchestration_scripts
│ ├── input
│ └── output

I've refactored the project accordingly, including the README.md. Please, let me know in case of any troubles with the scripts due to the refactoring.

I left placeholders for subfolders in the added `output` and `input` directories. I also left small files there. Some of them are outdated work-in-progress files, but I wanted to include rather more than less.

Please, let me know if any further clarification might be helpful.
