### ISSUE TITLE
issues with SamusRam / HPA-Cell-Segmentation

### ISSUE THREAD

**Issue by LiubovSobolevskaya** [SamusRam/hpa-single-cell#3]
Hi! Thank you very much for the implementation! 

I am trying to reproduce your results and I ran into some issues:
```python
cell_segmentations, init_sizes = segmentator.pred_cells(images, median_nuc_sizes=median_nuc_sizes)
```
resulted in the error:
```bash
TypeError: pred_cells() got an unexpected keyword argument 'median_nuc_sizes'
```

**Comment by SamusRam** [comment]
@LiubovSobolevskaya , thank you for noticing the issue and sorry for the inconvenience caused by my different work-in-progress versions of HPA-Cell-Segmentation tools.

Could you please install HPA-Cell-Segmentation from [this branch](https://github.com/SamusRam/HPA-Cell-Segmentation/tree/closer_to_orig)? I've added the installation instruction in the README.md, I've also modified the corresponding source code. Please, let me know in case of any further trouble.
