### ISSUE TITLE
get_new_class_name_indices_in_prev_comp_data() might have a bug

### ISSUE THREAD

**Issue by LiubovSobolevskaya** [SamusRam/hpa-single-cell#7]
Hi!

I was looking at the DensenetClass and it calls  get_new_class_name_indices_in_prev_comp_data  function. This function 
```python
returns list(new_name_index_2_old_name_index.keys()) 
```
what corresponds to indexes of new classes and not from the previous competition. The return value is 
```bash
>prev_class_name_indices  
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
```
Am I wrong or the right thing would be
```python
returns list(new_name_index_2_old_name_index.values()) 
```
with the result:
```bash
>prev_class_name_indices 
[0, 1, 2, 3, 4, 5, 6, 7, 11, 12, 14, 17, 19, 21, 23, 24, 25]
```
I have also a question: What is the reason for the following line in DensenetClass:
```python
prev_class_name_indices += [27, 27]
```
Since 8. Peroxisomes, 9. Endosomes,  10. Lysosomes, 20. Lipid droplets and 26.  Cytoplasmic bodies correspond to 17.Vesicles and punctate cytosolic patterns ? Won't any of these classes be a better choice for 17. Vesicles other than  27?

Thank you very much for your replies, it is much appreciated!

**Comment by SamusRam** [comment]
Hi, Люба! 

I believe that you know this codebase better than me, at this point :)

Yes, it's definitely a bug. 

In addition, the function `get_new_class_name_indices_in_prev_comp_data` smells:
1. Why are there `class_name_2_new_idx`? It can be deleted I believe.
2. I'm not sure if it's okay to rely on the insertion order of the dict, because it was not guaranteed before python3.6... but perhaps it's ok.

> Won't any of these classes be a better choice for 17. Vesicles other than 27?

might be.. Obviously, initialization was not so crucial, if even with this buggy transfer-learning initialization my model achieved reasonable performance. 
As you can see, during the competition I didn't even re-read some functions I wrote in a hurry. Thanks for going over the code! Please, feel free to propose your fix via pull request :)
